// Code generated by go-bindata.
// sources:
// config/mysql.yml
// config/storage.yml
// DO NOT EDIT!

package assets

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _configMysqlYml = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xb4\xce\x41\xae\xc2\x30\x0c\x84\xe1\xbd\x4f\x31\x27\xa8\x92\xd7\x27\x84\x7c\x19\xe4\x26\x2e\x20\xa5\x38\x8a\x5d\xb8\x3e\xea\x86\x35\x1b\x76\xb3\x99\x5f\x5f\xb3\x22\x8d\x09\x90\x5a\x87\xba\x33\x72\x9a\xd2\x94\xa7\x9c\x13\xcf\x73\x3a\x11\xb0\xbb\x0e\x46\x68\xc4\xdf\x4c\x40\x17\xf7\x97\x8d\xca\x9f\x45\x40\x95\x90\x45\x5c\x19\xeb\xb0\xeb\x72\x8f\x4b\xd5\xa7\x36\xeb\x9b\x3e\xe2\x38\x0d\x0b\x2b\xd6\x18\x51\x3a\x01\xe5\x26\xc3\x35\x18\x7b\xac\xe7\x6d\xf9\x27\x0a\xf5\xf8\x09\xe4\x08\x7f\x23\x78\x07\x00\x00\xff\xff\x8c\x67\x33\x28\x0b\x01\x00\x00")

func configMysqlYmlBytes() ([]byte, error) {
	return bindataRead(
		_configMysqlYml,
		"config/mysql.yml",
	)
}

func configMysqlYml() (*asset, error) {
	bytes, err := configMysqlYmlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "config/mysql.yml", size: 267, mode: os.FileMode(420), modTime: time.Unix(1508780974, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _configStorageYml = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x94\xcf\x41\xaa\x83\x40\x0c\xc6\xf1\xfd\x9c\x22\x17\x78\x2f\xa8\x3b\x2f\xe0\x09\xda\xad\xc4\x9a\xaa\xd4\x4c\x64\x92\xf6\xfc\x45\x29\xb4\x83\xa5\xe0\x6e\xf8\xf8\xfd\x03\xe3\x6c\x5e\x07\x00\x73\x4d\x34\xb0\xad\x6f\x80\x3f\x88\x24\x5c\x43\x3f\xd9\xad\xd8\x16\x80\x85\x7c\xac\xe1\x1f\x5d\x16\x7c\xe9\xb6\xa3\x99\xe2\x85\x53\xbb\x9e\xc1\xb7\xfe\xec\xcb\x43\x7d\xb9\xeb\xab\x43\x7d\x15\x42\xcf\x0f\x9e\x75\x11\x8e\xbf\x7e\x96\xb4\xd3\xec\x32\x4a\x74\xdc\x66\xbc\x26\x1d\xba\xc9\xb3\x20\x92\x15\x7b\xbf\xae\x5f\xf9\xa8\xc2\x39\x3f\x19\x27\x43\x67\xf7\xb2\xca\x68\x93\xbb\xb3\xce\x77\x61\xc3\x26\x3c\x03\x00\x00\xff\xff\xbc\x98\xce\xf9\x9c\x01\x00\x00")

func configStorageYmlBytes() ([]byte, error) {
	return bindataRead(
		_configStorageYml,
		"config/storage.yml",
	)
}

func configStorageYml() (*asset, error) {
	bytes, err := configStorageYmlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "config/storage.yml", size: 412, mode: os.FileMode(420), modTime: time.Unix(1508792066, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"config/mysql.yml": configMysqlYml,
	"config/storage.yml": configStorageYml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"config": &bintree{nil, map[string]*bintree{
		"mysql.yml": &bintree{configMysqlYml, map[string]*bintree{}},
		"storage.yml": &bintree{configStorageYml, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

